#!/usr/bin/env ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "debian/buster64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end
  config.vm.provider :libvirt do |v|
    v.memory = 1024
    v.cpus = 2
  end

  config.vm.define "ff-service" do |t|
    t.vm.hostname = "ff-services"
    t.vm.network "private_network",ip: "10.19.0.2", netmask: "255.255.0.0"
    t.vm.provision :shell, path: "bootstrap.sh"
    t.vm.network :forwarded_port, guest: 8833, host: 8833
  end
  
  # enable automatic update check:
  config.vm.box_check_update = true
  
  # make sure that guest additions is already installed with:
  # vagrant plugin install vagrant-vbguest
  # strange, not working:
  # config.vm.synced_folder "../", "/opt/ff-node-monitor"

end
